services:
  muscriptor-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: muscriptor-web
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /home/rtroiano/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8222:8222"
    networks:
      - web_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_network"
      - "traefik.http.routers.muscriptor.rule=Host(`muscriptor.exit-code.net`)"
      - "traefik.http.routers.muscriptor.entrypoints=websecure"
      - "traefik.http.routers.muscriptor.tls=true"
      - "traefik.http.routers.muscriptor.tls.certresolver=httpresolver"
      - "traefik.http.services.muscriptor.loadbalancer.server.port=8222"

networks:
  web_network:
    external: true
